### ISSUE TITLE
Autocomplete ERROR

### ISSUE THREAD

**Issue by ErrorCZE** [Nathaniel-VFX/Discord.js-v14-Command-Handlers#10]
![image](https://user-images.githubusercontent.com/47039176/189177258-accc22e7-78f6-4dc3-bf4c-b29b2f89fbad.png)
Hello, when I type something in option where autocomplete should work, it shows this error.
Probably because it wants to run the reply command right away ?

Any fix for it please ? :D Thanks

**Comment by SummerToast** [comment]
....... how can we know your code? if ur not sending it.

**Comment by Nathaniel-VFX** [comment]
This error is already fixed.

**Comment by SirHoDo** [comment]
> 
![image](https://user-images.githubusercontent.com/50068989/194894897-a3e26dec-649c-4c7b-91a2-0e6a7474a1a0.png)
Are you sure? Playing around with your autocomplete and it is still an issue

**Comment by mackhankins** [comment]
I keep getting this error on one of my commands.  What was the fix?

**Comment by mackhankins** [comment]
I see you're checking for value presence in https://github.com/Nathaniel-VFX/Discord.js-v14-Command-Handlers/blob/c89c64ba1f9fc11cb61fae557bd675546fe7cf93/slashCommands/fun/animal.js#L31.

That fixed it.

**Comment by mackhankins** [comment]
After some testing I think this is the way to fix this...

```js
  run: async (client, interaction) => {

    if (interaction.type === 2) {
```
